server:
  port: 9001
spring:
  rabbitmq:
    host: 122.51.105.58
    username: root
    password: 123456
  application:
    name: community-base
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://122.51.105.58:3306/community_friend?characterEncoding=UTF8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
eureka:
  client:
    service‐url:
      defaultZone: http://admin:123456@122.51.105.58:6868/eureka
  instance:
    prefer‐ip‐address: true
test_value: 111111111111111111
