server:
  port: 6868
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@122.51.105.58:${server.port}/eureka
spring:
  security:
    basic:
      enabled: true
    user:
      name: admin
      password: 123456
